name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'public/streamSchedule.json'
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'
      - 'public/**'
      - 'api/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'public/streamSchedule.json'
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'
      - 'public/**'
      - 'api/**'

jobs:
  # Fast linting and type checking
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
        
    - name: Install dependencies
      run: |
        npm ci --prefer-offline --no-audit --no-fund || npm install --prefer-offline --no-audit --no-fund
        
    - name: Run ESLint
      run: npm run lint:check --if-present || echo "ESLint completed with warnings"
      continue-on-error: true
      

  # Build and validate
  build-and-validate:
    name: Build & Validate
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
        
    - name: Install dependencies
      run: |
        npm ci --prefer-offline --no-audit --no-fund || npm install --prefer-offline --no-audit --no-fund
        
    - name: Validate JSON files
      run: |
        node -e "require('./public/streamSchedule.json')" && echo "✓ streamSchedule.json is valid"
        node -e "require('./public/24hourSchedule.json')" && echo "✓ 24hourSchedule.json is valid"
        node -e "require('./public/version.json')" && echo "✓ version.json is valid"
      
    - name: Build application
      run: npm run build

  # Security audit
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
        
    - name: Install dependencies
      run: |
        npm ci --prefer-offline --no-audit --no-fund || npm install --prefer-offline --no-audit --no-fund
        
    - name: Run security audit
      run: npm audit --audit-level=moderate
      continue-on-error: true
