# This workflow has been replaced by ci.yml
# Keeping for reference - can be deleted after confirming new CI works
name: JSON Validation Tests (DEPRECATED)

on:
  workflow_dispatch: # Only allow manual trigger

jobs:
  test-json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
        
    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit --no-fund
        
    - name: Run JSON validation tests
      run: npm run test:json
      
    - name: Run all tests with coverage
      run: npm run test:ci
      
    # Note: Discord integration tests (test:discord) are intentionally excluded
    # from CI/CD to prevent accidental webhook messages in production

